//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ayisigi_otel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciGirisKayitlari
    {
        public int Id { get; set; }
        public Nullable<int> KullaniciId { get; set; }
        public Nullable<System.DateTime> GirisTarih { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
