//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ayisigi_otel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdaDurumlari
    {
        public int Id { get; set; }
        public int OdaId { get; set; }
        public int MusteriId { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
        public virtual Odalar Odalar { get; set; }
    }
}
